---
- name: assert nginx folder
  become: yes
  file: path=/etc/nginx state=directory

  tags:
    - consul

- name: deploy nginx template
  become: yes
  copy:
    src: consul.nginx
    dest: /etc/nginx/templates/consul.nginx
  notify:
    - reload nginx
  tags:
    - consul

- name: write nginx config vars to the consul k/v
  run_once: yes
  command: >
    consul-cli kv-write --token={{ consul_acl_secure_token }}
    "{{ item.path }}" "{{ item.content }}"
  with_items:
    - path: secure/consul/nginx/do_ssl
      content: "{{ do_consul_ssl }}"
    - path: secure/consul/nginx/do_auth
      content: "{{ do_consul_auth }}"
  tags:
    - consul

- name: install nginx admin password
  become: yes
  run_once: yes
  command: consul-cli kv-write --token={{ consul_acl_secure_token }} secure/service/nginx/auth/users/admin '{{ nginx_admin_password_encrypted }}'
  when: nginx_admin_password_encrypted is defined
  tags:
    - consul

- name: enable nginx-consul
  become: yes
  service:
    name: nginx-consul
    enabled: yes
    state: started
  notify:
    - restart nginx-consul
  tags:
    - consul
