---
- name: configure lvm for mesos data
  become: yes
  template:
    src: 40-mesos-data-volume.conf.j2
    dest: /etc/mantl/filesystems.d/40-mesos-data-volume.conf
    mode: 0644
  when: lvm_physical_device != ""
  tags:
    - mesos
    - disk

- name: process with mantl storage setup
  become: yes
  shell: "/usr/bin/mantl-storage-setup"
  when: lvm_physical_device != ""
  tags:
    - mesos
    - disk

- name: create mesos work dir for non-lvm platforms
  become: yes
  shell: mkdir -p {{ mesos_work_dir }}
  when: lvm_physical_device == ""
  tags:
    - mesos
    - disk

- name: install follower configuration
  become: yes
  yum:
    name: "{{ mesos_agent_package }}"
    state: present
  tags:
    - mesos
    - bootstrap

- name: configure mesos-agent
  become: yes
  template:
    src: mesos-agent.sysconfig.j2
    dest: /etc/sysconfig/mesos-agent
  notify: remove mesos follower metadata
  tags:
    - mesos

- name: write credential
  when: do_mesos_follower_auth|bool
  become: yes
  copy:
    dest: /etc/sysconfig/mesos-agent-credential
    content: "{{ mesos_follower_principal }} {{ mesos_follower_secret }}"
    mode: 0600
  notify: restart mesos follower
  tags:
    - mesos

- name: delete credential
  when: not do_mesos_follower_auth|bool
  become: yes
  file:
    dest: /etc/sysconfig/mesos-agent-credential
    state: absent
  notify: restart mesos follower
  tags:
    - mesos

- name: write mantl-api credential
  when: do_mesos_framework_auth|bool
  become: yes
  template:
    src: mantl-api-credential.j2
    dest: /etc/sysconfig/mantl-api
    mode: 0600
  tags:
    - mesos

- name: delete mantl-api credential
  when: not do_mesos_framework_auth|bool
  become: yes
  file:
    dest: /etc/sysconfig/mantl-api
    state: absent
  tags:
    - mesos
