---
- name: remove mesos
  become: yes
  yum:
    name: mesos
    state: absent

- name: install mesos packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mesos_package }}"
    - cyrus-sasl-md5
  tags:
    - mesos
    - bootstrap

- name: ensure consul.d is present
  become: yes
  file:
    path: "{{ consul_dir }}"
    state: directory
  tags:
    - mesos

- name: create mesos entries for syslogd
  become: yes
  copy:
    dest: /etc/rsyslog.d/20-mesos.conf
    content: |
      # Mesos logging
      :syslogtag, isequal, "mesos-slave:"  /var/log/mesos/mesos-agent.log
      :syslogtag, isequal, "mesos-master:"  /var/log/mesos/mesos-master.log
      & ~
  notify:
    - restart rsyslog
  tags:
    - mesos

- meta: flush_handlers

- include: leader.yml
  when: mesos_mode == "leader" or mesos_mode == "mixed"

- include: follower.yml
  when: mesos_mode == "follower" or mesos_mode == "mixed"
