---
- name: reload unit files
  become: yes
  command: systemctl daemon-reload

- name: restart mesos leader
  become: yes
  command: systemctl restart mesos-master

- name: remove mesos follower metadata
  become: yes
  command: "{{ item }}"
  with_items:
    - systemctl stop mesos-agent
    - "rm -rf {{ mesos_work_dir }}/meta/slaves/latest"
    - systemctl start mesos-agent

- name: restart mesos follower
  become: yes
  command: systemctl restart mesos-agent

- name: restart nginx-mesos-leader
  become: yes
  command: systemctl restart nginx-mesos-leader

- name: reload nginx-mesos-leader
  become: yes
  command: systemctl daemon-reload

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted
