---
- name: create systemd service for managing swarm
  become: yes
  template:
    dest: "/usr/lib/systemd/system/swarm-{{ swarm_role }}.service"
    src: "swarm-{{ swarm_role }}.service.j2"
  notify:
    - reload systemd

- name: enable and start swarm-agent
  become: yes
  service:
    name: "swarm-{{ swarm_role }}"
    enabled: yes
    state: started
