---
- name: create kubernetes config directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/kubernetes"
    - "/srv/kubernetes"
    - "{{ kube_manifest_dir }}"
    - "{{ kube_podmaster_dir }}"
    - "{{ kube_cert_dir }}"
    - "{{ kube_users_dir }}"
  tags:
    - kubernetes

- name: generate kube-proxy manifest
  become: yes
  template:
    src: "kube-proxy.yml"
    dest: "{{ kube_manifest_dir }}/kube-proxy.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - kubernetes

- name: install kubernetes binaries
  become: yes
  yum:
    name: "{{ kubernetes_package }}"
    state: present
  tags:
    - kubernetes

- name: generate kubelet systemd unit
  become: yes
  template:
    src: kubelet.service.j2
    dest: /usr/lib/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - kubernetes

- name: generate kubelet kubeconfig
  become: yes
  template:
    src: "kubeconfig.yml.j2"
    dest: "/etc/kubernetes/kubeconfig.yml"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - kubernetes

- name: pull hyperkube docker image
  become: yes
  command: "docker pull {{ kube_hyperkube_image }}:{{ kube_hyperkube_image_tag }}"
  register: docker_pull_result
  changed_when: docker_pull_result.stdout.find('newer') > -1
  tags:
    - kubernetes

- include: secrets.yml
  tags:
    - secrets
    - kubernetes

- name: enable and start kubelet service
  become: yes
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - kubernetes
