---
- name: reload marathon
  become: yes
  command: systemctl daemon-reload
  notify:
    - wait for marathon to listen

- name: restart marathon
  become: yes
  command: systemctl restart marathon
  notify:
    - wait for marathon to listen

- name: wait for marathon to listen
  command: /usr/bin/smlr http "http://localhost:{{ marathon_port }}/ping"

- name: restart nginx-marathon
  become: yes
  command: systemctl restart nginx-marathon

- name: reload nginx-marathon
  become: yes
  command: systemctl daemon-reload
