- name: Calico ipPool configuration
  become: yes
  template:
    src: calico_ippool.yml.j2
    dest: /etc/calico/calico_ippool.yml
    owner: root
    group: root
    mode: 0644

- name: Calico profile configuration
  become: yes
  template:
    src: calico_profile.yml.j2
    dest: /etc/calico/calico_profile.yml
    owner: root
    group: root
    mode: 0644

- name: Calico directory for cni config
  become: yes
  file:
    path: /etc/kubernetes/cni
    state: directory
  tags:
    - calico

- name: Calico cni config for kubernetes
  become: yes
  template:
    src: calico-plugin.conf
    dest: /etc/kubernetes/cni/10-calico.conf
  tags:
    - calico
