---
- name: generate kubernetes manifests
  become: yes
  template:
    src: "{{ item }}.yml"
    dest: "{{ kube_manifest_dir }}/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kube-apiserver
    - kube-podmaster
    - kube-system
    - kube2consul
  notify:
    - restart kubelet
  tags:
    - master
    - kubernetes

- name: generate kubernetes consul services
  become: yes
  template:
    src: kubernetes-consul.json
    dest: /etc/consul/kubernetes-consul.json
    owner: consul
    group: consul
    mode: 0644
  notify:
    - reload consul
  tags:
    - master
    - kubernetes

- meta: flush_handlers
  tags:
    - kubernetes

- name: generate kubernetes podmaster manifests
  become: yes
  template:
    src: "{{ item }}.yml"
    dest: "/srv/kubernetes/manifests/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kube-scheduler
    - kube-controller-manager
  tags:
    - master
    - kubernetes

- name: wait for apiserver to come up
  wait_for:
    port: 8085
  tags:
    - kubernetes

- name: create kube-system namespace
  become: yes
  kube:
    resource: namespace
    name: kube-system
    filename: "{{ kube_manifest_dir }}/kube-system.yml"
    server: "http://127.0.0.1:{{ kube_insecure_port }}/"
    state: present
  run_once: true
  tags:
    - master
    - kubernetes

- name: configure kubectl
  become: no
  command: "/bin/kubectl {{ item }}"
  with_items:
    - config set-cluster mantl --server=http://127.0.0.1:8085
    - config set-context mantl --cluster=mantl --namespace=kube-system
    - config use-context mantl
  tags:
    - kubernetes

- name: register kube_default_token
  shell: /bin/kubectl describe secrets default-token | grep "token:" | sed -r 's/token:\s+//' | tr -d '\n'
  register: kube_token_out
  run_once: true
  tags:
    - kubernetes

- local_action: copy content={{ kube_token_out.stdout }} dest={{ playbook_dir }}/ssl/kubernetes/default-token
  tags:
    - kubernetes

- include: skydns.yml
  when: dns_setup
  tags:
    - kubernetes

- include: dashboard.yml
  when: enable_ui
  tags:
    - kubernetes
