---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart traefik
  become: yes
  command: systemctl restart traefik

- name: update-ca-trust
  become: yes
  command: update-ca-trust
