---
- name: generate consul config for NodePort services
  become: yes
  template:
    src: nodeport.json.j2
    dest: /etc/consul/nodeport.json
  notify:
    - reload consul
  tags:
    - node
    - kubernetes
